GET http://localhost:8080/usuarios
####
GET http://localhost:8080/usuarios/1
####
POST http://localhost:8080/ecommerce/usuarios
Content-Type: application/json

# {
#     "nomeUsuario": "Rorivaldo7",
#     "email": "rorivadfg7@gmail.com",
#     "senha": "1234567",
#     "telefone": "219929456297",
#     "perfil": "ADMIN"
# }

{
    "nomeUsuario": "Eduardo",
    "email": "teste@gmail.com",
    "senha": "654321",
    "telefone": "219929456288",
    "perfil": "USUARIO"
}


####
POST http://localhost:8080/ecommerce/usuarios/login
Content-Type: application/json

# {
#     "email": "rorivadfg7@gmail.com",
#     "senha": "1234567"
# }

{
    "email": "teste@gmail.com",
    "senha": "654321"
}

####
GET http://localhost:8080/ecommerce/categorias
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjk3NjkxMzA4LCJleHAiOjE2OTc3Nzc3MDh9.vo6f_-zJB3sQP3_7-7Adl260uFmDOGORrzhWvN55Tbg
//Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjk3NjkxNDc4LCJleHAiOjE2OTc3Nzc4Nzh9.m6jw9drhtU-6Dw5pq2G2k0_XN4XyxXt8OP4cHWnfViE"