GET http://localhost:8080/usuarios
####
GET http://localhost:8080/usuarios/1
####
POST http://localhost:8080/ecommerce/usuarios
Content-Type: application/json

{
    "nomeUsuario": "Rorivaldo7",
    "email": "rorivadfg7@gmail.com",
    "senha": "1234567",
    "telefone": "219929456297",
    "perfil": "ADMIN"
}
####
POST http://localhost:8080/ecommerce/usuarios/login
Content-Type: application/json

{
    "email": "rorivadfg7@gmail.com",
    "senha": "1234567"
}